name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Build Docker image
      run: docker build . -t digerate/my-node-beginner-app:${{ github.sha }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: docker push digerate/my-node-beginner-app:${{ github.sha }}

    - name: Save Docker image to tar.gz
      run: |
        docker save digerate/my-node-beginner-app:${{ github.sha }} | gzip > my-node-app.tar.gz

    - name: Copy Docker image to VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_SSH_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        port: 22
        source: "my-node-app.tar.gz"
        target: "/tmp"

    - name: Deploy on VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_SSH_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          gzip -d /tmp/my-node-app.tar.gz
          docker load < /tmp/my-node-app.tar
          docker stop my-node-app || true
          docker rm my-node-app || true
          docker run -d --name my-node-app -p 80:3000 digerate/my-node-beginner-app:${{ github.sha }}
